[project]
name = "magicworkshop"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pyside6>=6.10.1",
    "pyside6-fluent-widgets>=1.11.1",
]

[dependency-groups]
dev = [
    "nuitka>=2.7.0",
    "zstandard>=0.23.0",
    "ruff>=0.13.0",
]
