[project]
name = "magicworkshop"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pyqt6>=6.10.2",
    "pyqt6-fluent-widgets>=1.11.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
]
